spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lab_db
    username: postgres
    password: "050430"

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 开启SQL日志，便于观察
  global-config:
    db-config:
      id-type: auto
    # 改为你的密码